# Generated by Django 5.2.3 on 2025-10-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(upload_to='customer_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=20)),
                ('kudumbasree_details', models.CharField(max_length=90)),
                ('passbook', models.ImageField(upload_to='seller_passbooks/')),
            ],
        ),
    ]
