# Generated by Django 5.2.3 on 2025-10-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0014_orderitem_cost_price_product_cost_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
