# Generated by Django 6.0.8 on 2026-08-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0020_feedback_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='inspired_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
